project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550"
  page-footer:
    left: "fchen9@upenn.edu"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/frankc9912
        text: "Frank Chen GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/fang-chen-0648812b0/
        text: "Frank Chen LinkedIn"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/background.qmd
          - analysis/data_source.ipynb
          - analysis/exploratory.ipynb
          - analysis/prediction.ipynb
          - analysis/conclusion.qmd
format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
